service: anssijalauri-using-ses

provider:
  name: aws
  runtime: python2.7
  stage: dev
  region: 'eu-west-1'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ses:SendEmail
        - ses:SendRawEmail
      Resource: "*"  


functions:
  sendEmail:
    handler: handler.sendEmail
    description: This function will send an email
    events:
      - http:
          path: send-email
          method: post
          integration: lambda
          cors: true
          response:
            headers:
              "Access-Control-Allow_Origin": "'*'"


plugins:
  - serverless-python-requirements
